### ISSUE TITLE
XML Schema

### ISSUE THREAD

**Issue by pquackenbush** [rsanchez-wsu/fa15-ceg3120#1]
We need to develop a schema so that all parties involved know how the XML will be structured, what's a valid element, and so forth.

**Sample Idea**

``` XML
<jobrequest source="create or search">
    <users>
        <homeowner>
            <uid/>
            <name/>
            <email/>
            <address/>
            <phone/>
        </homeowner>
        <contractor>
            <uid/>
            <name/> <!-- company name or user name or both? -->
            <email/>
            <phone/>
        </contractor>
    </users>
</jobrequest>
```

**Comment by AKA-Syenite** [comment]
There's two approaches we can take with this, either we (the networking classes in aggregate) take raw xml and parse it (harder, less modular), or take normal parameters and do all the xml ourselves (modular, fewer points of failure). I feel the latter option is the better choice.

**Comment by nathanjent** [comment]
I was assuming that the xml would be created from class structures. The server and clients would need to have matching data sets that can be dynamically written to and read from XML and passed between.

**Comment by AKA-Syenite** [comment]
I mean, you can certainly take that approach, but it significantly increases coupling between modules.

**Comment by nathanjent** [comment]
You're right. Modular would be best.

**Comment by pquackenbush** [comment]
A third option would be to utilize a common parser (SAXON?) and builder that is shared among all modules.  You could then use a sub-class of the main parser to strip out only the pertinent elements that you need at the time, and the builder would only construct based on what was sent to it.

I feel that these modules will be coupled no matter how we try to approach this, as the clients will be required to supply the data that the server and database expect, and vice versa. Whether that data is in the form of objects, parameters, or XML.  However, if we all share a single XML constructor that throws exceptions when unrecognized elements are trying to be added, we have one point that needs edited to ensure all modules are on the same page.

Just an idea, I'm definitely open to criticism/other options

**Comment by AKA-Syenite** [comment]
That's also a possible way to do it, but I think it would be an overcomplicated wrapper when looking at the amount and type of data that actually needs to be passed between modules. (excluding encoding/decoding xml strings for network communications since we're required to use xml)

**Comment by nathanjent** [comment]
Yes, it should be part of the common core module.

**Comment by DevinJamesK** [comment]
I also agree.  No need to make it more complex then it has to be.

**Comment by jgotty777** [comment]
Late to the party, however I agree that modular is better.

**Comment by AKA-Syenite** [comment]
This also ties into #5
