### ISSUE TITLE
Unified Entry Point for Most Users

### ISSUE THREAD

**Issue by pquackenbush** [rsanchez-wsu/fa15-ceg3120#10]
Since this impacts just about every team, I thought that I'd create an issue for it.  I've created a bare bones main class in the core module to launch the login prompt. My thoughts are that the the user supplies UUID and pswd, clicks submit, a UserAccount obj is created, passed to Networking, and then waits for a more specific UserAccount obj to return from Networking (DB call to verify credentials and wait for profile info). After that, call launchGui() on the returned obj to launch the correct client.

Thoughts?

 I'll probably put a UML together or draw something in paint tomorrow night.

**Comment by SeanPWebb** [comment]
We were under a similar impression from the contractor GUI side.

**Comment by pquackenbush** [comment]
I think we are all on the same page here
