### ISSUE TITLE
Payment/Scheduling files not in a Package

### ISSUE THREAD

**Issue by pquackenbush** [rsanchez-wsu/fa15-ceg3120#14]
The files added to the repo Payment_Scheduling_Window.java, Tabbed_Frame.java, etc are not in any package.  Please create a package that will contain your source.

**Comment by jgotty777** [comment]
I don't know how to do that on git.

**Comment by emilynovak** [comment]
Ok, we'll look into it and fix it. Thanks!

**Comment by jgotty777** [comment]
Think i fixed it. I don't know if this is what you wanted. I just added the entire folder of the project from netbeans. Let me know if this works. 
Thanks,
Jason Gottweis
