### ISSUE TITLE
Create Login Window

### ISSUE THREAD

**Issue by pquackenbush** [rsanchez-wsu/fa15-ceg3120#15]
We need to get the base for this up so the other teams can have this code available.

At a minimum this needs:
JLabel > JTextfield
JLabel > JPasswordfield
JButton (Login)
JButton [or hyperlink type] (to launch CreateNewAccount window)

@CJMiller94

**Comment by pquackenbush** [comment]
Preliminary UI pushed to HomeownerUIBase.  Please take a look and feel free to add any comments, moans, gripes, or concerns.

**Comment by BKEcho** [comment]
Log in window GUI constructed
