### ISSUE TITLE
XML Networking Proposal

### ISSUE THREAD

**Issue by nathanjent** [rsanchez-wsu/fa15-ceg3120#19]
I propose we implement the network messages using Javabeans and XMLEncoder to serialize.

```
XMLEncoder e = new XMLEncoder(new BufferedOutputStream(new FileOutputStream("Test.xml")));
e.writeObject(new JButton("Hello, world"));
e.close();
```

JavaBean objects can be defined commonly and used by all the other components to transmit data. 
For example:
- A contractor enters date and time into the contractor GUI
- This information is put into a Schedule object
- A network message is created including the serialized Schedule object.
- The message is sent to the server as xml.
- The server deserializes the xml message and recreates the Schedule object
- The schedule object can then be passed on the the Scheduling engine

Let me know if you like the idea or propose your own ideas.

**Comment by cbensman** [comment]
I like this idea. The only question I would have is how would we know what object to recreate it as when deserializing it. From my understanding of this, when you deserialize an object, you cast it to the type object it should be.

**Comment by nathanjent** [comment]
Even though it is an Object it has the class name of the original object decoded from the xml.

```
if (obj.instanceof(Schedule) {
    // do the schedule things
}
```

Here's a more in depth example of JavaBeans xml serialization from the interwebs:
https://dzone.com/articles/javabeans-xml-no-libraries

**Comment by cbensman** [comment]
Got it, I did not fully understand how this worked. After reading the article, I feel that I have enough of a grasp to go on. I have another question, as far as the responsibilities of the core/database and the networking teams. Will my group (core/database) be responsible for opening our own networking socket and listening for messages from the networking team that is passing the serialized xml, or will the networking team have API for us to use that will allow us to get the deserialized objects and do the updating of the database / passing another object back to be serialized and relayed to the GUIs?

**Comment by nathanjent** [comment]
The networking team will create the serialization/deserialization methods. Once a deserialized object is received it should be routed to scheduling, payment, or database depending on the need. Scheduling and payment can further process the object or it could go directly to the database. A network message could be a pull request from the database or a push to the database. 
As for the JavaBean classes. it would probably be a good idea to have the database team define those based on the schema with input from other teams.

**Comment by DevinJamesK** [comment]
Looks good to me, seems to be the simplest way to do it.  That article was a useful read.

**Comment by nathanjent** [comment]
I think we are in agreement. Java Beans is go.
