### ISSUE TITLE
System Architecture

### ISSUE THREAD

**Issue by nathanjent** [rsanchez-wsu/fa15-ceg3120#2]
I've created a system architecture diagram. I made it using an open source software called [Dia](https://wiki.gnome.org/Apps/Dia). Please discuss the architecture here and feel free to post revised images.

![System Architecture Diagram](http://i.imgur.com/rfbKUz1.png)

**Comment by pquackenbush** [comment]
Just a thought, but if we agree on a single schema, then we could potentially pull the XML processing into a shared module that the Contractor, Homeowner and Server could all utilize.  Instead of each group writing their own parsers, we could extend the functionality of the shared resource.

**Comment by LABurn** [comment]
This evening @opcecco and I are going to go ahead and design an architecture that would be both more secure and more modular. With this in mind, we were thinking something closer to an extended UDP. I'll have an update for this in about an hour after deliberation.

**Comment by pquackenbush** [comment]
One issue that I could foresee with UDP is that there's no confirmation that the data was received, leaving the client in a limbo state to determine whether their transmission was received by the server.  Personally, I think receiving a response code from the server would make things slightly easier.  If you get a 200 response code, message received, continue on; otherwise, try again(or do something else).

I'm not 100% certain, but if we used RESTful clients, then we could POST, GET, etc to pass data from client to server and server to client.  I believe that would require an HTTP type connection though.

**Comment by rsanchez-wsu** [comment]
Please note that we will not be covering UDP in class. I am OK with having the option to have the clients communicate over both TCP and UDP (perhaps as a user-configurable option).  However, if only one will be implemented it needs to be TCP, as that is what will be covering in class.

**Comment by opcecco** [comment]
Does anyone here have any prior experience with RESTful clients? If we go that way, this could be a good way to learn, but going UDP or TCP could make for a less research-intensive project.

**Comment by LABurn** [comment]
Additionally, we risk involving ourselves in dependency hell if we continue to introduce more and more tools like this. Really what's being asked isn't enough to warrent a full blown API building framework in my opinion, when you can do a lot of data transfer and communication through an old fashioned networking schema.

**Comment by LABurn** [comment]
FYI, I have experience with both TCP and UDP.

**Comment by AKA-Syenite** [comment]
I have experience with both options, honestly it's up to whichever people are more comfortable with.

**Comment by pquackenbush** [comment]
LABurn brings up a valid point. I think we may be able to do everything we need with simple Socket connections, and that's a standard Java API. It may require some translating to get the format of the InputStream/OutputStream correct, but it shouldn't be too difficult.

We may be over thinking this.
