### ISSUE TITLE
Submit your feature requirements to Core Team

### ISSUE THREAD

**Issue by laanak08** [rsanchez-wsu/fa15-ceg3120#20]
All groups, please have your required features submitted to core team's Database entity models page very soon.
@pquackenbush 
@LABurn 
@jakern 
@emilynovak 
@BrianTighe

**Comment by pquackenbush** [comment]
Are you asking for the data types (and what fields they contain) that we will be asking to store in the DB? Or what type of queries that we'll need? Or, most likely, all the above and more?  I should have more time tonight or tomorrow before class starts to get what you're looking for to you.  

Also, if you're not getting responses fast enough, you can use the data types in common.data as a starting place for what the groups are thinking about storing.

**Comment by jakern** [comment]
You should also be able to get what most of the groups are going to need
the database for from their wiki pages

**Comment by laanak08** [comment]
DB is just the tip of what we're asking for. We got most of the DB stuff by just grazing the other team pages. Mostly looking for "logic features". UI pages should have minimal business logic, so we're asking UI teams to give us requirements for the business aspects of their page. In other words, "what does your page do, unrelated to rendering views that is core to the overall product?"

**Comment by pquackenbush** [comment]
It seems that we're on the same page as far as what the UIs are supposed to be doing.  From what I understand, all we're doing is collect data from the user packaging it and shipping it off, or asking for a collection of data and un-packaging it for display. By un-packaging I mean sifting the obj and presenting the data in human readable format.

From login:
- Login
  - send UserAccount obj with uuid and password
  - expected to receive UserAccount subclass correlating to uuid and password or some (atm undefined) invalid type
- CreateNewAccount
  - send UserAccount subclass
  - DB creates new account with profile fields provided (will vary depending on subclass)
  - expected to receive some type of confirmation
    - perhaps we could add a boolean field to UserAccount and receive a UserAccount with uuid=null, pswd=null, created=true/false
    - Or a string field that we could display in a popup. So the user can see that an account was created, already exists, or failed

From HomeownerUI:
- CreateNewJobRequest
  - Send JobRequest obj with HomeownerAccount obj
  - DB creates new job if identical job doesn't already exist
  - expected to receive confirmation
    - Could follow same ideas for CreateNewAccount
- GetOpenJobRequests
  - Send OpenJobRequests obj with HomeownerAccount obj
  - expected to receive all open jobs by the given user(not sure how to describe this with JavaBeans)

``` XML
            <concon>
                <JobRequest user="username1" field="plumbing">
                    <datafields/>
                    <bid contractor="con1"/>
                    <bid contractor="con2"/>
                </JobRequest >
                <JobRequest user="username1" field="electrical">
                    <datafields/>
                </JobRequest user="username1" field="construction">
                <JobRequest>
                    <datafields/>
                </JobRequest>
            </concon>
```
- PickBid
  - not 100% locked-down here yet

This is what I can come up with off the top of my head... I think we talked about using a pub-sub model for payment/scheduling.  So as far as that's concerned with the HomeownerUI, all we do is spawn their interface and wait for a notification that there's new data that needs displayed.

The only logic that I foresee at the moment is validating inputs before we ship the data off (i.e. a phone # field actually contains just numbers or numbers and hyphens).
