### ISSUE TITLE
Operating system level server controls

### ISSUE THREAD

**Issue by jakern** [rsanchez-wsu/fa15-ceg3120#21]
I had originally intended to have a server control GUI with OS level controls (via ssh) without taking into the account that we had not discussed the base platform. From there my question is should the admins has access to OS level controls from the GUI and if yes, would the networking group have any part in that or can it all be done via ssh?

**Comment by rsanchez-wsu** [comment]
@jakern , the controls should be limited to administering the ConCon platform.  That is, managing user accounts, managing data, etc.  I don't think that there should be a need for using ssh.
