### ISSUE TITLE
Please respect Checkstyle

### ISSUE THREAD

**Issue by samohtj** [rsanchez-wsu/fa15-ceg3120#23]
Please make sure that your branch is free from Checkstyle violations before you push it. Some of you aren't using Eclipse, and that's okay, but please realize that every Checkstyle violation becomes a compiler warning when you open the project in Eclipse. That means every single little formatting difference, including bracket positioning, becomes a big fat yellow thorn in my side. I'm tired of seeing that little yellow triangle on every single file.

So, even if you aren't using Eclipse, please make sure you are following our style restrictions. Some things to keep in mind:
- Javadoc comments **must** be present and **must** be filled out. All public methods should have one.
- Brackets must be on the same line as the method name/condition/whatever, separated by one space.
- Lines can't be longer than 100 characters
- Abbreviations/acronyms can't contain more than one capital letter. Example: encodeXml NOT encodeXML.
- Local variable names must be longer than just one character.

It may seem like these are small, insignificant, nit-picky details. But, when you have _dozens_ of them all over the place, it can make it harder to find actual problems because it floods the project with warnings.

I've already gone through a branch or two and fixed all the problems I found, but I haven't looked at the rest. It would really benefit everyone to make sure we all follow the same style. It makes merging across branches _much_ easier. I don't want to spend all day fixing merge conflicts that arise from style differences.

**Comment by rsanchez-wsu** [comment]
@samohtj I have not had an opportunity to add CheckStyle to the command-line build like I did for FindBugs.  I may get to it tomorrow, but you are welcome to look at how I did it for FindBugs and implement something similar for CheckStyle that fails the build if any violations are found.  Incidentally, this (the merging of work of numerous programmers across branches) is one reason why I really like CheckStyle.  It helps to minimize the churn and keeps everything looking consistent.

**Comment by pquackenbush** [comment]
Should we add something like this to checkstyle?  The tab vs spaces makes merging a complete nightmare.

``` xml
<module name="RegexpSinglelineJava">
    <property name="format" value="^\t* "/>
    <property name="message" value="Indent must use tab characters"/>
    <property name="ignoreComments" value="true"/>
</module>
```

**Comment by rsanchez-wsu** [comment]
I am OK with that.  I honestly thought that I already had that check in there, but I must have overlooked it.  Feel free to add it.

**Comment by BKEcho** [comment]
Has been added and pushed to master
