### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by nathanjent** [rsanchez-wsu/fa15-ceg3120#3]
I've created a high level use case diagram. I made it using an open source software called [Dia](https://wiki.gnome.org/Apps/Dia). Please discuss the use cases here and feel free to post revised images.

![Use Case Diagram](http://i.imgur.com/ZFNv3HA.png)

**Comment by rsanchez-wsu** [comment]
@nathanjent, thanks for moving these diagrams into issues.  There is certainly an argument to support having them in the repository, but in the case of our group it makes more sense to have them attached to issues.  It facilitates better discussion and collaboration.

That said, I like how you are focusing on the system components in #2 and the actor interactions here.  Too often people dive right into implementation details without understanding what the system really needs to do.

Unfortunately, we can't spend too long on this or we won't get any coding done.  However, this is a worthwhile discussion and encourage everyone to contribute.
