### ISSUE TITLE
un-version .ipr and .iws files from git. For master and all other branches.

### ISSUE THREAD

**Issue by laanak08** [rsanchez-wsu/fa15-ceg3120#30]
They are IntelliJ IDE specific files, and not relevant to the project. They are environment specific files.
@pquackenbush 
@LABurn 
@jakern 
@emilynovak 
@BrianTighe

**Comment by AKA-Syenite** [comment]
The eclipse files are similarly tracked.

**Comment by rsanchez-wsu** [comment]
@laanak08 @Shukaro 

I am OK with IDE project files being version control.  For one thing, it makes it easier to share CheckStyle settings, FindBugs settings, etc.  However, I have made sure that all the Eclipse files in Git have only project-relative references in them.  If the IntelliJ files only have project-relative references then in my mind they are no different than the Eclipse project files.  However, if they are specific to a particular user's environment (e.g., references to files or resources in the user's home directory, or to the specific JDK location on the user's system), then they should not be in Git.

**Comment by AKA-Syenite** [comment]
That is indeed the case. (No user-specific data)

**Comment by laanak08** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/206827587-How-to-manage-projects-under-Version-Control-Systems

This is my proposition for how we should be handling the versioning of IntelliJ files. Additionally, note that .ipr/.iws are of the legacy system, and that .iws files are specifically mentioned to contain user-specific settings.
