### ISSUE TITLE
2 contractor GUI's 

### ISSUE THREAD

**Issue by SeanPWebb** [rsanchez-wsu/fa15-ceg3120#32]
Would it greatly offend anyone if i deleted the impostor contractor GUI branch?  The one with lower case GUI, isn't ours and we're not sure what its purpose is.

**Comment by samohtj** [comment]
That branch is almost 100 commits behind, so I think it's safe to say it's unused. If it's not yours, you  should be safe to delete it.

**Comment by SeanPWebb** [comment]
alright im gonna axe it
