### ISSUE TITLE
TELL US WHAT MESSAGES YOU WANT TO SEND

### ISSUE THREAD

**Issue by AKA-Syenite** [rsanchez-wsu/fa15-ceg3120#36]
We need to know what kind of messages you want to send from client->server and what kind of responses you need to send back server->client. (All communications are initiated by the client, for obvious reasons.)

**Comment by jakern** [comment]
Besides chat messages and database queries?

**Comment by AKA-Syenite** [comment]
Basically we just need to know the events on which you'll send a message (IE ClientQueryMessage, ClientQueryResponse)

**Comment by AKA-Syenite** [comment]
We don't really need to know any arguments though.

**Comment by nathanjent** [comment]
I added a section to the Networking Wiki page that we need for everyone to expand on.
https://github.com/rsanchez-wsu/fa15-ceg3120/wiki/Networking

**Comment by cbensman** [comment]
If we are planning on implementing notifications, we will need a way for clients to subscribe to the database/core. I don't know if this should be opened as another issue but I'm assuming this will be done by having them opening a connection with the networking stack and then having it block and tracking the client. Do you guys have any plans for this? Also does anybody in the GUI groups have any light to shed as far as if they are planning on doing this, and if so what kind of notifications do they want te receive?

**Comment by AKA-Syenite** [comment]
The need for this is resolved as of b91f4c45d67751f771bf7bf398530deab3798cd3
