### ISSUE TITLE
Database Update Handling

### ISSUE THREAD

**Issue by QLaVell** [rsanchez-wsu/fa15-ceg3120#4]
We need to decide how the view will update when the database is updated while a user is viewing it.

Current ideas are to:
1. Notify user that database has changed and request a refresh
2. Automatically refresh view
3. Periodically refresh view
4. Do nothing assess conflicts afterwards

Does anybody else have any ideas?

**Comment by nathanjent** [comment]
What data is being updated? If it is search results just update when they hit a search button. Messages update when received from other users. Winning bids or completed work should update when other users submit them like messages. The only need I could see using constant updates is logging in the server gui.

**Comment by pquackenbush** [comment]
I agree, the only thing I could see that would really be nice to know is if a contractor was looking at a list of all of their open bids and ended up winning one. But they should be getting a notification of some kind pushed to them when they win a bid making this redundant. Perhaps there's a use case outside of the Server UI I'm just not seeing(metadata processing).

**Comment by rsanchez-wsu** [comment]
There are several possibilities here.

First, the core/database layer could keep track of what views have been requested and what clients are connected (remember we are using TCP) then actively notify the clients that their views are stale.  Alternatively, the core/database layer could keep track but not notify the clients, only raising some sort of "exception"-like response if an update is attempted on a stale view.

There are other possibilities as well, but those two should get the discussion going.

**Comment by katrinaScott** [comment]
I personally like the idea of pushed notifications more, but I recognize that the reactionary, "exception"-type response is probably easier to implement and more functional in nature (sort of a "why should I care it's changed unless it poses a problem for me?" mindset). I know within the homeowner UI we were comparing the idea of having a "newsfeed"-like activity record vs a more active, push notification system, so perhaps if we (the collective UI groups) decide we want the activity items/notifications to be pushed to the user, we could just do the same with refresh requests (and vice versa- if we don't want things to be quite as complex/dynamic, the database can simply wait until a problem appears before notifying the user).
I'm really curious to see what others will add to this conversation as it's a pretty key aspect of how we implement our respective interfaces, but I know that I, personally, don't have the knowledge to argue for which would be "better" outside of just "I think this would be neat" (which is about the least useful thing to add to a conversation) haha

**Comment by cbensman** [comment]
I'm not 100% positive on the implementation of this, but an idea that I had would be a trigger system on the backside, that when triggered after an update to the database would send a "message" to the clients letting them know that something in a specific table in the database had been changed. This would leave it up to the groups building the front end GUIs to decide based on what has been changed, if they think the components that the user currnetly is viewing should be refreshed, or else ignore the message. I could also see this being unnecessary, as it may just be easier to only refresh the clients view after they have done something, like click the search button, or just receive push notifications that something has changed.

**Comment by jakern** [comment]
_**First, the core/database layer could keep track of what views have been requested and what clients are connected (remember we are using TCP) then actively notify the clients that their views are stale. *_*

I think this is one of the best solutions. The server can notify the client that something the client is looking at has changed and then we leave it up to the clients to decide when to update itself. For example if the Contractors were looking at jobs we would want their view of available jobs to refresh as fast as possible but realistically, if we were dealing with a large number of users, this would not work so well. We'd only want the clients to fetch new data when they click a "view more results" button or such. For direct messaging and winning a bid a regular push notification and immediate refresh would be encouraged.

**Comment by nathanjent** [comment]
If a contractor is looking at a list of jobs we can fetch the status of the job if he tries to select one then alert him that the job is no longer available. The list would then refresh on load. At most I would only allow it to refresh at 1 second or greater intervals, and even then only at the server's leisure.
