### ISSUE TITLE
Proposed Networking Model

### ISSUE THREAD

**Issue by AKA-Syenite** [rsanchez-wsu/fa15-ceg3120#5]
I committed a possible type of implementation we could pursue to the networking branch. (78af71719d7508189f728d9ed56d48f4e0af2b82)

In this model (as it stands) the client initiates all communications and the server listens via `@NetworkHandler` annotations.

@nathanjent, @DevinJamesK, @Opcecco, @LABurn, @parishalexander, @Shukaro

**Comment by AKA-Syenite** [comment]
When the server receives a message it should almost certainly break out to posting it onto the bus then collect any responses from the `@NetworkHandler`'s and send those back, on the same socket to be posted clientside, rather than the current after-the-fact posting behavior. Would let clients use `@NetworkHandler`'s to process response messages.

Would probably also want to constrain `@NetworkHandler` registration so that people couldn't subscribe multiple to the same message.

**Comment by LABurn** [comment]
Couldn't subscribe multiple what to the `@NetworkHandler`?

**Comment by AKA-Syenite** [comment]
Multiple `@NetworkHandler`'s that listen for the same message to the network bus.
