### ISSUE TITLE
PLEASE DEVELOP ON BRANCHES INSTEAD OF MASTER

### ISSUE THREAD

**Issue by AKA-Syenite** [rsanchez-wsu/fa15-ceg3120#6]
As the title says, please do dev-work on branches seperate from `master`, and then only merge them when they're stable(ish) to keep the main branch relatively functional and clean. See [Branch Development](https://github.com/rsanchez-wsu/fa15-ceg3120/wiki/Branch-Development) for more specific details.

**Comment by pquackenbush** [comment]
Just a note:

If you want to merge into a specific branch, you need to have the branch that you are merging into checked-out. So if I wanted to merge the networking branch into HomeownerUIBase, I would first need to checkout HomeownerUIBase:
`git checkout HomeownerUIBase` (This step is unneeded if you are merging into a branch that you already have checked out for development)

Then perform the merge:
`git merge origin/networking`

if there are any merge conflicts, you can use `git status` to see the current status of your merge which will include merge conflicts. [A great tutorial on resolving merge conflicts](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

Commit your merge:
`git commit <message>`
or you can use `git commit` and edit the message in the text editor. Type `:wq` to exit and submit the generated msg (git will see you are committing a merge and slap on its default merge msg).

Push your commit to the repo:
`git push origin HomeownerUIBase`

Feel free to edit this if I missed something, or have incorrect steps here. I usually have to look up the merging process each time, and wrote this from memory

**Comment by rsanchez-wsu** [comment]
Don't forget that if you have tags you can specify --tags to git and will push them.  Also, if you want to push all branches and not have to specify which ones to push, 'git push --mirror' will do the trick.
