### ISSUE TITLE
Team 5: Create and populate database

### ISSUE THREAD

**Issue by samohtj** [rsanchez-wsu/fa15-ceg3120#61]
Create a small program to create an empty database with all the tables and fields that we've defined, and fill it with dummy data. People should be able to run it once, and have a functioning database to use for testing.

**Comment by nathanjent** [comment]
You don't need to write a program, just have them run an SQL script that creates all the tables and populates with dummy data.

**Comment by edennewitz** [comment]
That is what I was planning on doing

**Comment by edennewitz** [comment]
[Table Design.txt](https://github.com/rsanchez-wsu/fa15-ceg3120/files/53041/Table.Design.txt)
[inserts.txt](https://github.com/rsanchez-wsu/fa15-ceg3120/files/53042/inserts.txt)
copy and paste the contents,do table design first to build tables and it will default to the app schema then run the copy paste the inserts to fill with dummy data (if you don't make the tables in the app schemea the insert statements will need to be updated by replacing the word app in each insert to what ever schema you put it in)
