### ISSUE TITLE
Polymorphic Design for User Accounts

### ISSUE THREAD

**Issue by pquackenbush** [rsanchez-wsu/fa15-ceg3120#9]
I've gone ahead and added a UserAccount class with three subclasses in the core module.  This will allow us to easily launch the specific UI depending on the UserAccount subclass returned after logging in.

Added this to the tracker to test whether I could still tie a commit to a certain issue. _fingers crossed_

**Comment by pquackenbush** [comment]
Note:

This is still on the HomeownerUIBase branch

**Comment by pquackenbush** [comment]
I had a thought that perhaps we should have another package like ...common.data for the common ADTs that will be utilized like the User Account types, perhaps a JobRequest class, AvailableJobRequest class, and so forth.

This would help keep the core module more organized.

**Comment by rsanchez-wsu** [comment]
@pquackenbush, good call on both the polymorphic user account types and the core data objects.

**Comment by pquackenbush** [comment]
I think everyone is on the same page here. No need to keep this open methinks...
